### PR TITLE
CPC-157 Add China docker registry repo in k8s-rds

### PR DESCRIPTION
**Pull request by tokyo2006**
- because network is not good ,we should use our repo
- add a param named repository default is ""

### CODE REVIEW

**Review by sorenmat — APPROVED** [review]
LGTM
But I guess a better solution would be to do a PR against the main repo where you can specify the repository from the commandline?

**Comment by tokyo2006** [comment]
> LGTM
> But I guess a better solution would be to do a PR against the main repo where you can specify the repository from the commandline?

Yes, that's best way ,but for now we only have one repo in China. Global have no network issue to get image from `hub.docker.com`

**Comment by sorenmat** [comment]
LGTM but I think you should do the PR against sorenmat/k8s-rds :)

**Comment by sorenmat** [comment]
closing, I think the PR was made to the main repository

**Pull request closed without merging**
